function SA240513151130 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SA240513151130 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SA240513151130 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  SA240513151130 = importfile("/Users/tillecki/Library/CloudStorage/OneDrive-Aarhusuniversitet/Master Electrical Engineering/2. Semster/Energy System Integration/Project/Loaddata/DatenAnalyse/New Folder/SA_240513151130.csv", [32, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-May-2024 15:15:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [32, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["MachineModule", "SpectrumAnalyzer", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["MachineModule", "SpectrumAnalyzer"];
opts.VariableTypes = ["double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
SA240513151130 = readtable(filename, opts);

end